### ISSUE TITLE
Block-Cortana Error

### ISSUE THREAD

**Issue by aluminoobie** [EnclaveConsulting/SANS-SEC505#1]
Ran the script with -Verbose and received the following error:
New-NetFirewallRule : Cannot process argument transformation on parameter 'Package'. Cannot convert value to type System.String

Corrected the error adding double quotes to line 94:
$AppFilter = "Get-NetFirewallRule -DisplayGroup 'Cortana' -Direction Outbound | Get-NetFirewallApplicationFilter"

Its minor but thought I would share.

**Comment by JasonFossen** [comment]
Hi Aluminoobie:
Thanks for you feedback, but I can't reproduce your error.  If you post more details, like OS version and PoSh version, I might be able to track it down.  
Thanks,
   J.

**Comment by aluminoobie** [comment]
I'm using Windows 10 (10.0.15063.0) and Powershell 5.0 (5.1.15063.413).  I am running the script in a shell with administrator privileges.

Here is the full error:
New-NetFirewallRule : Cannot process argument transformation on parameter 'Package'. Cannot convert value to type
System.String.
At C:\users\123\desktop\Block-Cortana.ps1:95 char:263
+ ... bound UDP/TCP Traffic (Scripted)' -Package $AppFilter.Package | Out-N ...
    + CategoryInfo          : InvalidData: (:) [New-NetFirewallRule], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,New-NetFirewallRule

**Comment by JasonFossen** [comment]
Hi A:
I'm still not able to reproduce your error, but I've made a change to the script to try to help force the cast to a string.  When you run the following two lines, do you get any output?

------start----------
$AppFilter = Get-NetFirewallRule -DisplayGroup 'Cortana' -Direction Outbound | Get-NetFirewallApplicationFilter

$AppFilter.Package.ToString()
------end----------

The output should be similar to "S-1-15-2-1861897761-1695161497-2927542615-642690995-327840285-2659745135-2630312742."

If you get nothing, it seems the Cortana package does not exist or has been renamed or ???

Thanks,
   J.

**Comment by aluminoobie** [comment]
Thank you.  I get out similar to your example.  I'm not sure why my system behaves differently.  I may keep toying with sting inputs to see what could be causing it.

**Comment by aluminoobie** [comment]
I would be ok closing the issue.  I think the change you made should be enough for most situations.
